on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: setup git config
        run: |
          git config --global user.email "mapcolonies@gmail.com"
          git config --global user.name "mapcolonies"

      - name: Bump new version
        run: npm run release

      - name: Push git tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MC_WRITE_ACCESS_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Push to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
